### ISSUE TITLE
Update version to not confuse auto updater

### ISSUE THREAD

**Issue by lufog** [ionthedev/ReSprytile#11]
I downloaded version 0.8.0 and after installation version 0.7.1 is displayed. Also, auto update constantly shows that an update to 0.8.0 is available for the add-on. 

It would also be a good idea to update the [releases link in the ReadMe](https://github.com/ionthedev/ReSprytile#download) so that it does not redirect to another repository and is not misleading.

**Comment by ionthedev** [comment]
Thank you so much for pointing this out. Fixed and updated! Release is 0.8.1 now.
