### ISSUE TITLE
Tile selector doesn't show up on Blender 4.0

### ISSUE THREAD

**Issue by darltrash** [ionthedev/ReSprytile#15]
The tile selector does not show up whenever I click on the Build tool or any of the ReSprytile tools

More info:
- OS: Fedora Workstation 38
- Running Blender 4.0
- ReSprytile version: Master

**Comment by ionthedev** [comment]
I have been able to replicate the issue. Currently investigating

**Comment by Taron686** [comment]
for those who are interested, the override with` bpy.ops.sprytile.gui_win(override_context, 'INVOKE_REGION_WIN') `is no longer possible when switching to 4.0  , with the change below it will run further, but then the next Problem will start
```
area=override_context['area']
space_data=override_context['space_data']
region=override_context['region']
with bpy.context.temp_override(area=area,space_data=space_data,region=region):
        bpy.ops.sprytile.gui_win('INVOKE_REGION_WIN')
```
maybe it's just a problem with my installation, but with 4.0 the bgl function are all None, so the code has to be rewritten towards gpu

**Comment by darltrash** [comment]
Any updates?

**Comment by Taron686** [comment]
I made a fork and created a release, there are probably still a lot of bugs, but Sprytile starts at least

**Comment by Kaffeebohnson** [comment]
Any updates on the missing Tile Selector? I am on Blender 3.6 and it also disappeared. I can't get it to show back up.

**Comment by ionthedev** [comment]
@Taron686 did a great job making it work with Blender 4.X, Merged and Closed

https://github.com/ionthedev/ReSprytile/releases/tag/1.0.2
