### ISSUE TITLE
Working with larger sprite/tilesheets

### ISSUE THREAD

**Issue by BrahRah** [ionthedev/ReSprytile#7]
I've noticed that zooming in and moving the sheet only works inside the blender windows bounds. It would be better if the zoom and move would go through the bounds. Otherwise it's not possible to select on large sheets:
![Screenshot 2023-10-09 12:48:38](https://github.com/ionthedev/ReSprytile/assets/40721994/08752103-ed23-4fcf-a616-1f50b7ac531b)

**Comment by ionthedev** [comment]
Fixed in v0.8.0
