### ISSUE TITLE
Grid vanishes when set to 1x1

### ISSUE THREAD

**Issue by BrahRah** [ionthedev/ReSprytile#8]
2x2:
![Screenshot 2023-10-09 13:39:21](https://github.com/ionthedev/ReSprytile/assets/40721994/536f22a4-06f0-4614-88d2-b5eda6872505)
1x2:
![Screenshot 2023-10-09 13:39:34](https://github.com/ionthedev/ReSprytile/assets/40721994/a3198a8c-e8c6-4ff4-89bb-d9d53a7275a7)

**Comment by ionthedev** [comment]
Fixed in v0.8.0
